FROM node:20-alpine AS build
WORKDIR /src
COPY package.json package.json
RUN npm install
COPY . . 
RUN npm run build

FROM node:20-alpine
COPY --from=build /src/dist /dist
RUN npm install -g serve
CMD ["serve","-s","/dist/"]