apiVersion: v1 
kind: Service
metadata:
  name: client-svc
  namespace: client
spec:
  selector:
    key: app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---

apiVersion: v1 
kind: Service
metadata:
  name: cities-svc
  namespace: cities
spec:
  selector:
    key: app
  ports:
  - protocol: TCP
    port: 3142
    targetPort: 3142
  type: ClusterIP

--- 

apiVersion: v1 
kind: Service
metadata:
  name: mountains-svc
  namespace: mountains
spec:
  selector:
    key: app
  ports:
  - protocol: TCP
    port: 3143
    targetPort: 3143
  type: ClusterIP
