FROM golang:1.23.2 AS build
WORKDIR /src
COPY go.mod go.mod
RUN go mod download 
COPY . .
RUN CGO_ENABLED=0 go build -o app main.go

FROM alpine:latest
COPY --from=build /src/app /app
EXPOSE 3142
CMD ["/app"]