FROM node:20-alpine 
WORKDIR /src
COPY package.json package.json
RUN npm install
COPY . . 
CMD ["npm","start"]

# RUN npm run build

# FROM node:20-alpine
# COPY --from=build /src/dist /dist
# EXPOSE 3143
# CMD ["node","/dist/index.js"]